### ISSUE TITLE
翻訳エラー

### ISSUE THREAD

**Issue by rtakeuch331** [AdobeDocs/commerce-learn.ja-JP#1]
Issue in ./help/videos/cloud/1-overview.md

【現在の翻訳】用のクラウドガイド Commerce
【正しい翻訳】Commerce 用のクラウドガイド
【原文】　　　Cloud guide for Commerce

**Comment by mak-adobe** [comment]
ありがとうございます。G11N-11211のチケットで調査を開始しました。

**Comment by mak-adobe** [comment]
@rtakeuch331 修正が完了しました。ご協力ありがとうございました。
